#!/usr/bin/env python3
# util_readme_scrip_programs.py -- the README's SCRIP (hybrid) PROGRAM GRID, generated, never typed (Lon 2026-09-27, in-chat to the ceo,
# verbatim: "Do mention Rebus and Snocone in the README, however the benchmarks and test-suites are not interesting so do NOT publish those
# grids. But for SCRIP, do show a grid of programs working."; ceo CEO-1325). One row per program of the scriptix-demos population: its title
# and the languages its fenced sections carry (read from the .md document itself), and its mode-3 and mode-4 verdicts from the NEWEST
# scriptix-demos pass in the progress DB (the rows test_demos_suite.sh scriptix writes, one per program and mode). The block sits between two
# marker lines in SCRIP/README.md and names the SCRIP and corpus trees of the pass it read.
#   python3 .github/scripts/util_readme_scrip_programs.py --write | --check
# rc 0 written / current · rc 1 --check found the block stale · rc 2 cannot measure (no pass, no README markers, no corpus).
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
HOME = os.environ.get('S4E_HOME') or os.path.normpath(os.path.join(HERE, '..', '..'))
README = os.path.join(HOME, 'SCRIP', 'README.md')
DEMOS = os.path.join(HOME, 'corpus', 'demos', 'scriptix')
DB = os.environ.get('S4E_PROGRESS_DB', '/home/resources/progress/results.tsv')
BEGIN, END = '<!-- SCRIP-PROGRAMS:BEGIN', '<!-- SCRIP-PROGRAMS:END -->'
def refuse(why): sys.stderr.write('REFUSE(rc=2): ' + why + '\n'); sys.exit(2)
rows = []
with open(DB, 'rb') as fh:
    fh.seek(0, 2); fh.seek(max(0, fh.tell() - 80_000_000))
    for raw in fh:
        c = raw.decode('utf-8', 'replace').rstrip('\n').split('\t')
        if len(c) > 9 and c[5] == 'scriptix-demos' and c[8] in ('m3', 'm4'): rows.append(c)
if not rows: refuse('no scriptix-demos row in the progress DB -- run bash SCRIP/scripts/test_demos_suite.sh scriptix')
last = max(rows, key=lambda c: c[0]); scrip, corpus = last[1], last[2]
run = [c for c in rows if c[1] == scrip and c[2] == corpus]
verdict = {}
for c in sorted(run, key=lambda c: c[0]): verdict[(c[7], c[8])] = c[9]
progs = sorted({p for p, m in verdict})
if not progs: refuse('the newest scriptix-demos pass names no program')
def describe(prog):
    path = os.path.join(HOME, 'corpus', prog)
    if not os.path.isfile(path): return '', ''
    t = open(path, encoding='utf-8', errors='replace').read()
    langs = []
    for m in re.finditer(r'(?m)^```([A-Za-z0-9+#]+)', t):
        if m.group(1) not in langs: langs.append(m.group(1))
    title = ''
    m = re.search(r'SCRIP DEMO\s*\d+\s*-+\s*(.+?)\s*(\(|$)', t, re.M)
    if m: title = m.group(1).strip()
    if not langs and prog.endswith('.sno'): langs = ['SNOBOL4']
    return title, ' · '.join(langs)
mark = {'PASS': '✅', 'FAIL': '❌', 'CRASH': '💥', 'HANG': '⏳'}
both = sum(1 for p in progs if verdict.get((p, 'm3')) == 'PASS' and verdict.get((p, 'm4')) == 'PASS')
out = [BEGIN + ' generated by .github/scripts/util_readme_scrip_programs.py --write from the progress DB\'s newest scriptix-demos pass '
       '(SCRIP ' + scrip + ', corpus ' + corpus + ', measured ' + last[0][:10] + ') -- do not edit by hand -->',
       '', '**%d of %d programs pass in both modes** against their refs on their sample input (`bash scripts/test_demos_suite.sh scriptix`):' % (both, len(progs)),
       '', '| Program | What it does | Languages in one file | mode 3 | mode 4 |', '|:---|:---|:---|:---:|:---:|']
for p in progs:
    title, langs = describe(p)
    v3, v4 = verdict.get((p, 'm3'), '—'), verdict.get((p, 'm4'), '—')
    note = ''
    if 'no-ref' in ' '.join(c[11] for c in run if c[7] == p and len(c) > 11): note = ' (no ref yet)'
    out.append('| `%s` | %s | %s | %s %s | %s %s |' % (p.replace('demos/scriptix/', ''), (title or '—') + note, langs or '—', mark.get(v3, ''), v3, mark.get(v4, ''), v4))
out.append(END)
block = '\n'.join(out)
if not os.path.isfile(README): refuse('no README at ' + README)
text = open(README, encoding='utf-8').read()
if text.count(BEGIN) != 1 or text.count(END) != 1: refuse('README needs exactly one %s line and one %s line' % (BEGIN, END))
a = text.index(BEGIN); z = text.index(END) + len(END)
new = text[:a] + block + text[z:]
if '--check' in sys.argv:
    print('SCRIP program grid: ' + ('current' if new == text else 'STALE'))
    sys.exit(0 if new == text else 1)
if '--write' in sys.argv:
    open(README, 'w', encoding='utf-8', newline='\n').write(new)
    print('SCRIP program grid: %d program(s), %d both-modes PASS, from the pass on SCRIP %s' % (len(progs), both, scrip)); sys.exit(0)
print(block)
